name: Contracts Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0

      - name: Lint
        run: forge fmt --check

      - name: Build
        run: forge build --deny-warnings

      - name: Run tests
        run: forge test -vvv
